<?php
global $waves_elements;
$waves_elements["fonticon"] = array(
    "name" => "Font Icon",
    "only" => "shortcode",
    "size" => "col-md-4",
    "settings" => array(
        "fi" => array(
            "title" => "Add Icon",
            "type" => "fi",
            "holder" => "",
            "default" => "",
            "desc" => "",
        ),
        "fi_size" => array(
            "need_fi" => "true",
            "title" => "Size",
            "type" => "hidden",
            "holder" => "",
            "default" => "28",
            "desc" => "Size.",
        ),
        "fi_padding" => array(
            "title" => "Padding",
            "type" => "hidden",
            "holder" => "",
            "default" => "25",
            "desc" => "Padding.",
        ),
        "fi_color" => array(
            "title" => "Color",
            "type" => "hidden",
            "holder" => "",
            "default" => "#fff",
            "desc" => "Color.",
        ),
        "fi_bg_color" => array(
            "title" => "Background Color",
            "type" => "hidden",
            "holder" => "",
            "default" => "#6DAEB7",
            "desc" => "Background Color.",
        ),
        "fi_border_color" => array(
            "title" => "Border Color",
            "type" => "hidden",
            "holder" => "",
            "default" => "",
            "desc" => "Border Color.",
        ),
        "fi_rounded" => array(
            "title" => "Border Size",
            "type" => "hidden",
            "holder" => "",
            "default" => "0",
            "desc" => "Border Size.",
        ),
        "fi_rounded_size" => array(
            "title" => "Border Rounded Size",
            "type" => "hidden",
            "holder" => "",
            "default" => "50",
            "desc" => "Border Rounded Size.",
        ),
        "fi_box_shadow" => array(
            "title" => "Box Shadow Inset?",
            "type" => "select",
            "options" => $waves_element_options['yesno'],
            "default" => "false",
        ),
        "fi_rotate" => array(
            "title" => "Rotate ?",
            "type" => "select",
            "options" => $waves_element_options['yesno'],
            "default" => "false",
        ),
        "fi_icon" => array(
            "title" => "Icon",
            "type" => "hidden",
            "holder" => "",
            "default" => "fa-cloud",
            "desc" => "Icon.",
        ),
    ),
);